In [1]:
import numpy as np

In [2]:
a = np.array([[12,34,5],[45,5,2]])

In [3]:
a.sum(axis=1)

array([51, 52])

In [4]:
b= np.array([[1,2,5],[4,5,6]])

# Dot product by using transpose

In [5]:
a.dot(b.transpose())

array([[105, 248],
       [ 65, 217]])

In [6]:
len(dir(np))

600

In [7]:
np.cross(b,a)

array([[-160,   55,   10],
       [ -20,  262, -205]])

# Sorting the array

In [8]:
%%time
np.sort(a,axis=0)

CPU times: total: 31.2 ms
Wall time: 1 ms


array([[12,  5,  2],
       [45, 34,  5]])

In [9]:
%%time
np.sort(a,axis=0, kind='mergesort')

CPU times: total: 15.6 ms
Wall time: 997 µs


array([[12,  5,  2],
       [45, 34,  5]])

In [10]:
%%time
np.sort(a,axis=0, kind='quicksort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[12,  5,  2],
       [45, 34,  5]])