In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b = np.array([1,35,67,89,23,4,45,3,56,54,7,5,4,5,3,234])
b = b.reshape(4,4)
b

array([[  1,  35,  67,  89],
       [ 23,   4,  45,   3],
       [ 56,  54,   7,   5],
       [  4,   5,   3, 234]])

In [5]:
b = b.reshape(2,8)

In [6]:
b

array([[  1,  35,  67,  89,  23,   4,  45,   3],
       [ 56,  54,   7,   5,   4,   5,   3, 234]])

# argsort,argmin&argmax

In [11]:
np.argsort(b,axis=1)

array([[0, 7, 5, 4, 1, 6, 2, 3],
       [6, 4, 3, 5, 2, 1, 0, 7]], dtype=int64)

In [8]:
np.argmin(b)

0

In [9]:
np.argmax(b)

15

In [14]:
c= np.arange 

SyntaxError: invalid syntax (996911529.py, line 1)